- project:
    name: openstack/ansible-role-k8s-keystone
    check:
      jobs:
        - ansible-role-k8s-keystone-kubernetes-centos
        - ansible-role-k8s-keystone-openshift-centos

- job:
    name: ansible-role-k8s-keystone-kubernetes-centos
    parent:  ansible-role-k8s-base
    nodeset: ansible-role-k8s-centos
    vars:
      coe: kubernetes
      project_name: ansible-role-k8s-keystone
      ansible_role_k8s_required:
        - ansible-role-k8s-mariadb
    required-projects:
      - openstack/ansible-role-k8s-mariadb

- job:
    name: ansible-role-k8s-keystone-openshift-centos
    parent:  ansible-role-k8s-base
    nodeset: ansible-role-k8s-centos
    vars:
      coe: openshift
      project_name: ansible-role-k8s-keystone
      ansible_role_k8s_required:
        - ansible-role-k8s-mariadb
    required-projects:
      - openstack/ansible-role-k8s-mariadb
